apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
    app: mongodb
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  peristentVolumeReclaimPolicy: Retain 
  nfs:
    server: 192.168.1.108 # Replace this IP with 10.10.15.5, 10.10.15.9 or 10.10.15.34 depending which server is alloted to you
    path: /var/nfs/jegan/mongodb # Replace this path with your path /var/nfs/user[xy]/mysql
