apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-bc
  labels:
    name: hello
spec:
  triggers:
  - type: ConfigChange
  source:
    type: Git
    git:
      uri: "https://github.com/tektutor/openshift-july-2024.git"
      ref: main
    contextDir: "Day5/spring-ms"
  strategy:
    jenkinsPipelineStrategy: 
    jenkinsfilePath: ./Jenkinsfile

  output:
    to:
      kind: ImageStreamTag
      name: 'tektutor-hello:latest'
