apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-{{.Values.yourname}}
  labels:
    name: {{.Values.yourname}} 
    app: {{.Values.mariadb.app}} 
spec:
  capacity:
    storage: {{.Values.mariadb.pvSize}} 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  nfs:
    server: {{.Values.nfs.serverIP}} 
    path: {{.Values.mariadb.pvPath}} 
