apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-jfrog-bc
  labels:
    name: hello
spec:
  triggers:
  - type: ConfigChange
  source:
    type: Git
    git:
      uri: "https://github.com/tektutor/openshift-july-2024.git"
      ref: main
    contextDir: "Day5/buildconfig/hello-microservice"
  strategy:
    type: Docker
  output:
    to:
      kind: DockerImage 
      name: "tektutorjuly2024.jfrog.io/jegan-docker/hello-spring-microservice:1.0"
    pushSecret: 
      name: private-jfrog-image-registry
         
