apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-bc
  labels:
    name: hello
spec:
  triggers:
  - type: ConfigChange
  source:
    type: Git
    git:
      uri: "https://github.com/tektutor/openshift-july-2024.git"
      ref: main
    contextDir: "Day5/buildconfig/hello-microservice"
  strategy:
    customStrategy:
      from:
        kind: DockerImage
        name: docker.io/maven:3.6.3-jdk-11 
  output:
    to:
      kind: ImageStreamTag
      name: 'tektutor-hello:2.0'
