apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-jegan # Replace 'jegan' with your name
spec:
  selector:
    matchLabels:
      name: jegan
      app: mysql
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Mi
